### ISSUE TITLE
Shift whitelist of the 1.21 version mod doesn't work

### ISSUE THREAD

**Issue by miclol** [NyakoFox/VeinDigging#10]
Even after changing blocks to block and pack format to 48, shifting doesn't cause any of the listed blocks to vein mine. It used to have worked in the 1.20 version. Have not tested in 1.20.5/6.
Datapack: [VeinDigWhitelist.zip](https://github.com/user-attachments/files/15989254/VeinDigWhitelist.zip)

**Comment by NyakoFox** [comment]
1.0.2 just went up, might take a while for it to be accepted. When it does, does it fix the problem?

**Comment by miclol** [comment]
Unfortunately, it did not fix the issue.

**Comment by NyakoFox** [comment]
Hmm, it works for me. You don't have the mod client-side, right?

**Comment by miclol** [comment]
I was testing it in a single player world (so I guess I have it on both client and server side), placed a bunch of diamond ore, and mined it while shifting with a diamond pickaxe both in creative and survival mode, neither worked. Maybe some mod in the fabulously optimized modpack is interfering with it? Although I would have no idea why that would be the case.
I have not yet tested it purely on the server side.

**Comment by NyakoFox** [comment]
If you have the mod on client-side, shift veindigging is disabled, as you can use the keybind instead.

**Comment by miclol** [comment]
I'll update the server mod from 1.0.1 to 1.0.2 to test then.

**Comment by miclol** [comment]
Can confirm works with 1.0.2 on a 1.21 Fabric server.
