### ISSUE TITLE
Block Blacklist not working (Fabric 1.20.1)

### ISSUE THREAD

**Issue by Knito58** [NyakoFox/VeinDigging#14]
I want to stop myself from accidently destroying my builds.
I want to stop vein mining for cobblestone and stone_bricks for now. Later polished versions of stones may be added. This may stop destroying a base in one click.

In the config I set the additional values
 
  "useGlobalBlacklist": true,
  "useBindBlacklist": false,
  "useShiftBlacklist": false,
 
In the data folder of the main fabric profile I added the path

veindigging/tags/blocks

my global_blacklist.json looks like this:

{
  "values": ["minecraft:cobblestone","minecraft:stone_bricks" ]
}

After that didn't work I also did that in the saves folder for my singleplayer world.

It just not works. Veindigging mines my cobblestones in one click.

Where is my error?

**Comment by NyakoFox** [comment]
It's supposed to go in a datapack!

**Comment by Knito58** [comment]
Yes. Thank you. It works.
