### ISSUE TITLE
How to configure the veinmining whitelist?

### ISSUE THREAD

**Issue by psmpm** [NyakoFox/VeinDigging#6]
I understand the block tagging system and all that, but how do I add custom tags to a type of block (like all sand)?

**Comment by NyakoFox** [comment]
To reference a tag from another tag, you'd do `#minecraft:sand` to reference the sand tag.

**Comment by psmpm** [comment]
> To reference a tag from another tag, you'd do `#minecraft:sand` to reference the sand tag.

right but how do i add the `#minecraft:sand` tag to the `#veindigging:shift_whitelist` tag
i can't find anything useful about block tags online

**Comment by NyakoFox** [comment]
You'll have to do it in a datapack, [this might help](https://minecraft.wiki/w/Tutorials/Creating_a_data_pack)

**Comment by psmpm** [comment]
I got it, thank you
